### ISSUE TITLE
no more updates?

### ISSUE THREAD

**Issue by crossflow85** [leoniDEV/covid-19-report-ita#14]
Hi, there is a glitch in data at June 25 and no more updates since June 28.
Please could you keep your project going on? This is the best report and I'm worried that it might be abandoned!
Thank you very much!

**Comment by leoniDEV** [comment]
I'm very sad that I had to abandon the project I had a lot of ideas to implement, add new visuals and graphs in the report, improve and automate the updates and many others either in the backend and frontend. This was a good way for me to experiments with many things (CI/CD workflows, new .Net features, PowerBI, etc.) but my work has absorbed me completely in these months, so I didn't have time to devote to this project.

I didn't even find time to make a statement about the retirement of this project.

I'm sorry ☹
