### ISSUE TITLE
Problem with "Liguria" map

### ISSUE THREAD

**Issue by ferradario** [leoniDEV/covid-19-report-ita#2]
![image](https://user-images.githubusercontent.com/8653807/77533046-74af0b80-6e96-11ea-9d67-4b3f95d4ef19.png)

When trying to visualize the "Liguria" data, the maps shows Tuscany provinces instead.

**Comment by ulmozzz** [comment]
Folow up da issue #3 
Avevo visto questa issue 

Visto che vedo il problema ora (26 marzo, ore 10 a.m.) deduco che non possa essere stato pienamente corretto. Sbaglio? O forse, semplicememente, il file usato online dal sito "https://covid19-ita.leonidev.com/" non è allineato a quel build?

Prove fatte:
- cancellare chache
- usare versione sul sito "app.powerbi.com"
- usare un browser diverso, in cui il sito non è mai stato apert
- usare un device diverso (android)
- usare un device diverso (iPhone)
in tutti i casi il problema c'è ancora

Da come vedo, **il problema è stato corretto solo per la vista "valori assoluti" e non per la vista "incidenza"**.

A livello di pura SPECULAZIONE (mi piacerebbe sapere se ci ho preso) potrebbe essere che si selezionino sulla mappa le "regioni" con un particolare indice nell'array invece che le "province". 
Infatti selezionando sulla tabella in alto a destra le province "per nome" (Genova, La Spezia, etc.) la mappa si aggiorna mostrando di volta in volta una sola regione delle 4, senza suddivisione per province.
Questo è veramente un _blind shot_, l'ho aggiunto solo per curiosità

Grazie ancora per il sito comunque. Molto utile e ben fatto.

**Comment by ulmozzz** [comment]
ho notato anche altri "glitches"

sono minori, sempre relativi alle mappe

fammi sapere se vuoi che li segnali

come detto, sarei anche interessato a contribuire per risolverli, ma mi sembra siano all'interno di codice non pubblicato, quindi non posso farci nulla

se mi sbaglio, fammi sapere

**Comment by leoniDEV** [comment]
Certo che è allineato con la build e tutto il materiale che ho usato è nel repo (dovesse mancare qualcosa basta segnalarlo e lo metto a disposizione)

Per la mappa a pagina 4 serve il file provincie.json.
Ho verificato ancora e tutto sembra funzionare bene dalla mia parte, adesso ho provato a rinominare il file provincipe.json in prov.json.

Fammi sapere se si risolve anche da parte tua, dopo di che chiudo l'issue se tutto è andato bene

**Comment by leoniDEV** [comment]
Nevermind ho trovato il problema, è stata una mia dimenticanza da pivello 😳 (magari anche un po' la stanchezza visto che ci sto ancora lavorando da tutta la notte per implementare un sistema migliore per aggiornare i dati).

In realtà le mappe sono 2 sovrapposte, una per la vista con i numeri assoluti ed una con la vista con l'incidenza, quando si attiva in una vista se ne spegne una e quando si attiva l'altra vista si spegne l'altra.
Ho corretto la mappa nella vista con i dati assoluti ma non quella con i dati relativi all'incidenza.

**Comment by ulmozzz** [comment]
certamente, era chiaro fosse una svista, visto che credo fosse lo stesso baco di ieri

appena vedo la issue chiusa riprovo, per ora sembra non sia cambiato nulla

fammi sapere se ti interessano anche gli altri _minor bugs_

**Comment by leoniDEV** [comment]
certo che mi interessano.

Per io aspetto tue conferme per chiudere, da me sembrano funzionare tutte e due le mappe

**Comment by ulmozzz** [comment]
confermo che ora funziona anche a me

riguardo al resto, si è corretto con questa release; avevo notato che, sempre in modalità "incidenza", se per esempio per Lombardia cliccavi in tabella in alto a destra sulla riga BRESCIA, la mappa mostrava la Basilicata
![Brescia_Basilicata](https://user-images.githubusercontent.com/62692521/77644127-de93e780-6f60-11ea-8ae5-4c170de40da0.gif)

sempre come _minor thing_ (non è degna nemmeno lontanamente di chiamarsi bug, 
Se clicchi su una provincia sulla tabella in alto a destra con i "valori assoluti", la mappa fa zoom sulla provincia

![Lombardia_assoluti](https://user-images.githubusercontent.com/62692521/77644539-6c6fd280-6f61-11ea-8d38-8dffcd2fc956.png)

se invece fai la stessa cosa in modalità "incidenza" la mappa continua a mostrare la regione
![Lombardia_incidenza](https://user-images.githubusercontent.com/62692521/77644564-7c87b200-6f61-11ea-838d-1a4d8887c3e1.png)

Personalmente preferirei un ibrido: lasciare la regione (che è facilmente riconoscibile dall'utente) ma colorerei la provincia in modo diverso, evidenziandola. Così come accade (in entrambe le visualizzazioni), se invece di cliccare sulla RIGA della TABELLA clicchi sulla provincia all'interno della mappa

![Lombardia_click_su_mappa](https://user-images.githubusercontent.com/62692521/77644786-e56f2a00-6f61-11ea-8329-c17d0e885a5a.png)


Ovviamente sono commenti da profano che non deve fare il lavoro, vedi tu.

Ciao!

**Comment by leoniDEV** [comment]
Il comportamento corretto è quello che avviene nella vista dei valori assoluti, almeno era quello che pensavo fosse più adeguato, per il resto non posso fare niente, non ho molto controllo sul comportamento delle visual, il modo in cui queste reagiscono ai filtri ed agli slicer è al di fuori del mio controllo
