### ISSUE TITLE
Visualizzazione mappa Liguria 

### ISSUE THREAD

**Issue by ulmozzz** [leoniDEV/covid-19-report-ita#3]
alla pagina 4 di
https://covid19-ita.leonidev.com/
quando si seleziona "Liguria" la mappa in basso a destra mostra invece le regioni del "centro-nord" italia (Emilia, Toscana, Marche, Umbria)

Mi piacerebbe correggere direttamente io, ma non sono riuscito a capire come fare, quindi lascio solo la issue

ottimo lavoro comunque

(ho visto che c'era già una issue aperta ieri, ma il problema si è ripresentato)

**Comment by ulmozzz** [comment]
problema simile, in vista "incidenza" anche per la Valle d'Aosta, che mostra invece (coincidenza) la Liguria NON suddivisa per province

**Comment by leoniDEV** [comment]
Il problema è già stato segnalato in questa issue #2 
ed è stato corretto nel commit b759625

**Comment by leoniDEV** [comment]
Prova a svuotare la cache, sia in Power Bi Desktop, sia su Power Bi service vedo le mappe giuste selezionando le regioni giuste.
Chiudo questa come duplicato, se continui ad avere problemi anche dopo aver svuotato la cache la riapro l'issue l'altra issue
