### ISSUE TITLE
Mouse-over

### ISSUE THREAD

**Issue by laruzzante** [leoniDEV/covid-19-report-ita#4]
Nella mappa disponibile alla slide 4 mi pare aver notato una discrepanza nel valore riportato di casi tototali per provincia quando si comparano i numeri riportati dal mouse-over e quelli della tabella in alto a destra.

In allegato un esempio con la provincia di Varese.

<img width="419" alt="Screenshot 2020-04-17 at 13 17 51" src="https://user-images.githubusercontent.com/38459199/79563862-ddf8f780-80ad-11ea-9bed-bf300ba5525c.png">

**Comment by leoniDEV** [comment]
problema risolto, grazie per la segnalazione
